@startuml
set separator none
title Processus d'inscription à un événement

top to bottom direction
skinparam ranksep 60
skinparam nodesep 30

skinparam {
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}

hide stereotype

skinparam person<<Administrateur>> {
  BackgroundColor #08427b
  FontColor #ffffff
  BorderColor #052e56
  shadowing false
}
skinparam person<<AncienActuelJoueur>> {
  BackgroundColor #08427b
  FontColor #ffffff
  BorderColor #052e56
  shadowing false
}
skinparam rectangle<<ASHSAlumni.GestiondesUtilisateurs>> {
  BackgroundColor #438dd5
  FontColor #ffffff
  BorderColor #2e6295
  roundCorner 20
  shadowing false
}
skinparam rectangle<<ASHSAlumni.GestiondesÉvénements>> {
  BackgroundColor #438dd5
  FontColor #ffffff
  BorderColor #2e6295
  roundCorner 20
  shadowing false
}
skinparam rectangle<<ASHSAlumni.Historisation>> {
  BackgroundColor #438dd5
  FontColor #ffffff
  BorderColor #2e6295
  roundCorner 20
  shadowing false
}
skinparam rectangle<<ASHSAlumni>> {
  BorderColor #0b4884
  FontColor #0b4884
  shadowing false
}

rectangle "ASHS Alumni\n<size:10>[Software System]</size>" <<ASHSAlumni>> {
  rectangle "==Gestion des Utilisateurs\n<size:10>[Container: Fonctionnel]</size>\n\nEspace de gestion des comptes d'accès et authentification" <<ASHSAlumni.GestiondesUtilisateurs>> as ASHSAlumni.GestiondesUtilisateurs
  rectangle "==Gestion des Événements\n<size:10>[Container: Fonctionnel]</size>\n\nEspace de gestion des soirées retrouvailles et inscriptions" <<ASHSAlumni.GestiondesÉvénements>> as ASHSAlumni.GestiondesÉvénements
  rectangle "==Historisation\n<size:10>[Container: Fonctionnel]</size>\n\nEspace de traçabilité et conservation des historiques" <<ASHSAlumni.Historisation>> as ASHSAlumni.Historisation
}

person "==Ancien/Actuel Joueur\n<size:10>[Person]</size>\n\nMembre des équipes 1 de l'ASHS souhaitant participer aux retrouvailles" <<AncienActuelJoueur>> as AncienActuelJoueur
person "==Administrateur\n<size:10>[Person]</size>\n\nGestionnaire de l'application avec droits étendus" <<Administrateur>> as Administrateur

Administrateur -[#707070,thickness=2]-> ASHSAlumni.GestiondesÉvénements : "<color:#707070>1. 1. Définit les dates de soirée"
AncienActuelJoueur -[#707070,thickness=2]-> ASHSAlumni.GestiondesÉvénements : "<color:#707070>2. 2. Consulte les événements disponibles"
ASHSAlumni.GestiondesÉvénements -[#707070,thickness=2]-> ASHSAlumni.GestiondesUtilisateurs : "<color:#707070>3. 3. Vérifie que l'utilisateur est associé à un contact validé"
AncienActuelJoueur -[#707070,thickness=2]-> ASHSAlumni.GestiondesÉvénements : "<color:#707070>4. 4. S'inscrit à la soirée"
ASHSAlumni.Historisation -[#707070,thickness=2]-> ASHSAlumni.GestiondesÉvénements : "<color:#707070>5. 5. Enregistre l'inscription"
@enduml