services:
  structurizr-lite:
    image: structurizr/lite:latest
    ports:
      - "8080:8080"
    volumes:
      - ./dsl:/usr/local/structurizr
      # Optionnel : mapper images exportées pour y accéder facilement
      - ./images:/usr/local/images
    environment:
      - STRUCTURIZR_WORKSPACE_PATH=/usr/local/structurizr
