export const CONTACT_STATUSES: ContactStatus[] = ['SUBMITTED', 'NOT_REQUESTED', 'UNREACHABLE','SENDING','WAITING','VALIDATED'];

export type ContactStatus = 'SUBMITTED' | 'PENDING' | 'VALIDATED' | 'NOT_REQUESTED' | 'UNREACHABLE' | 'SENDING' | 'WAITING';
